// <auto-generated />
using System;
using DoraAPF.org.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DoraAPF.org.Data.Migrations
{
    [DbContext(typeof(DoraAPFContext))]
    [Migration("20190616225638_ChangeStringLengthForVisitorLog")]
    partial class ChangeStringLengthForVisitorLog
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DoraAPF.org.Data.Entities.VisitorLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BrowserName")
                        .HasMaxLength(150);

                    b.Property<string>("LocationIP")
                        .HasMaxLength(100);

                    b.Property<DateTime>("VisitedOn");

                    b.HasKey("Id");

                    b.ToTable("VisitorLog");
                });
#pragma warning restore 612, 618
        }
    }
}
